### ISSUE TITLE
Error: run_NeuronChat

### ISSUE THREAD

**Issue by rootze** [Wei-BioMath/NeuronChat#2]
Hello @Wei-BioMath 
Thanks for developing this tool. I had an error when running run_NeuronChat.

```
data.input_5xFAD_HEMI <- GetAssayData(NucSeq_5xFAD_HEMI, assay = "RNA", slot = "data") # normalized data matrix
dim(data.input_5xFAD_HEMI)

labels_5xFAD_HEMI <- Idents(NucSeq_5xFAD_HEMI)

meta_5xFAD_HEMI  <- data.frame(Celltypes = labels_5xFAD_HEMI, row.names = names(labels_5xFAD_HEMI))


cellchat_5xFAD_HEMI <- createNeuronChat(object = data.input_5xFAD_HEMI, meta = meta_5xFAD_HEMI, group.by = 'Celltypes', DB='mouse')

cellchat_5xFAD_HEMI <- run_NeuronChat(cellchat_5xFAD_HEMI,M=100)

```
Error after running run_NeuronChat: 
```
Error in apply(lig_contributor_expr_tmp[, rep_coeff], MARGIN = 1, function(x) exp(mean(log(x)))) :
  dim(X) must have a positive length
```

Regards,
Ze

**Comment by Wei-BioMath** [comment]
Hi @rootze, thank you for using NeuronChat. I guess the problem resides in `createNeuronChat`. The usage is slightly different from CellChat, and we need to assign the cell group labels (rather than a column name of `meta`) to `group.by`. Could you try `cellchat_5xFAD_HEMI <- createNeuronChat(object = data.input_5xFAD_HEMI, meta = meta_5xFAD_HEMI, group.by = meta_5xFAD_HEMI$Celltypes, DB='mouse')`? Let me know if this still doesn't work.

**Comment by rootze** [comment]
Thank you!

**Comment by anastasiiaNG** [comment]
@Wei-BioMath,

thank you for the nice tool.

I faced the same error, fixed it by the way you suggest, but after that faced another error:

```
> datmat <- as.matrix(whole.integrated@assays$SCT@scale.data)
> datmat[1:2, 1:2]
      AAACCTGCAAAGAATC-1_1 AAACCTGCAAAGTGCG-1_1
Lrp11            0.4644282           -0.4921679
Nup43            1.0934738           -0.3481221
> dim(datmat)
[1] 9925 3522

> metmat <- whole.integrated@meta.data[, c(1,9,20)]
> head(metmat, 2)
                     orig.ident genotype clusters
AAACCTGCAAAGAATC-1_1 Sample1  control            A
AAACCTGCAAAGTGCG-1_1 Sample2  control            B
> dim(metmat)
[1] 3522    3

> x <- createNeuronChat(object = datmat,
                      DB = "mouse",
                      meta = metmat,
                      group.by = metmat$clusters)


> x <- run_NeuronChat(x, M=100)

Error in if (M == 0 | max(prob_mtx) == 0) { :
  missing value where TRUE/FALSE needed

Warning:
1: In log(x) : NaN produced
2: In log(x) : NaN produced
...
```
  Could you please help to fix it?
Thank you!

**Comment by Wei-BioMath** [comment]
Hi @anastasiiaNG , I noticed the data you used have negative values, which probably cause the issue. The input data for NeuronChat should be log normalized without being scaled. For example, seurat.object@assays$RNA@data if you have already run the `NormalizeData` function.

**Comment by anastasiiaNG** [comment]
@Wei-BioMath, thanks, that helped!
